name: call_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  bloc: ^8.1.2
  cached_network_image: ^3.2.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  http: ^1.1.0
  json_annotation: ^4.8.1
  jwt_decoder: ^2.0.1
  open_ui: 
    path: open_ui/

dev_dependencies:
  build_runner:
  flutter_gen_runner:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:     
         - assets/
         - assets/images/
  fonts:
    - family: Graphik
      fonts:
        - asset: assets/fonts/GraphikLCG-Medium.otf
        - asset: assets/fonts/GraphikLCG-Regular.otf

flutter_gen:
  output: lib/assets/
  line_length: 120
